### ISSUE TITLE
Uncaught (in promise) TypeError: res.headers.get is not a function

### ISSUE THREAD

**Issue by ton212** [websanova/vue-auth#26]
I'm running Vue 1.0.26, Vue-Router 0.7.13, Vue-Resource 0.8.0 and the latest version of vue-auth.

I'm experiencing `Uncaught (in promise) TypeError: res.headers.get is not a function` error when I do `resource.get()`, that route is not protected by vur-auth and I didn't setup the auth API url yet.

Is it normal, and is it somthing to do with vue-auth?

```
Uncaught (in promise) TypeError: res.headers.get is not a function(…)

_getHeaders @ vue.1.0.0.js?a52b:27
_responseIntercept @ auth.js?9c12:88
(anonymous function) @ vue.1.0.0.js?a52b:60
(anonymous function) @ vue-resource.common.js?2f13:1049
(anonymous function) @ vue-resource.common.js?2f13:1048
```

**Comment by ton212** [comment]
By the way it does not product this error without vue-auth

**Comment by websanova** [comment]
Ya, it's a bit of a mess with all the versions because there have been so
many changes.  Try updating all your packages to the latest including
vue-auth.

**Comment by ton212** [comment]
All dependencies are at their latest version :/

**Comment by websanova** [comment]
Well vue resource is already at 1.0.x

**Comment by websanova** [comment]
https://github.com/vuejs/vue-resource/releases

**Comment by ton212** [comment]
After I update vue-resource to 1.0.2, this issue solved.

Don't know why I run `npm update` but the vue-resource didn't get updated :/

**Comment by FerchoCarcho** [comment]
npm install vue-resource@1.0.0 for  v1.1.0-beta  with TypeError: res.headers.get is not a function

**Comment by websanova** [comment]
Make sure you get latest versions of pre 2.0 packages.
